const NO_YES_OPTIONS = {
  NO: 'No',
  YES: 'Yes'
}

const COUNTRY_BIRTH_OPTIONS = {
  ARGENTINA: '13',
  GERMANY: '82',
  NEW_ZEALAND: '153',
}

const COUNTRY_ADDRESS_OPTIONS = {
  ARGENTINA: '13',
  GERMANY: '82',
  NEW_ZEALAND: '153',
}

const GENDER_OPTIONS = {
  MALE: 'M',
  FEMALE: 'F',
}

const PREFERED_TITLE_OPTIONS = {
  MR: '1',
  MRS: '2',
  MS: '3',
  MISS: '4',
  DR: '5',
  OTHER: '6',
}

const COMUNICATION_METHOD_OPTIONS = {
  EMAIL: '1',
}

const OTHER_IDENTIFICATION_TYPE_OPTIONS = {
  DRIVER_LICENSE: '1',
  BIRTH_CERTIFICATE: '2',
  NATIONAL_ID: '3',
}

module.exports = {
  NO_YES_OPTIONS,
  COUNTRY_BIRTH_OPTIONS,
  COUNTRY_ADDRESS_OPTIONS,
  GENDER_OPTIONS,
  PREFERED_TITLE_OPTIONS,
  COMUNICATION_METHOD_OPTIONS,
  OTHER_IDENTIFICATION_TYPE_OPTIONS
}